# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/
# and all available linters at https://megalinter.io/latest/all-linters/

# Apply fixes automatically
APPLY_FIXES: all
APPLY_FIXES_EVENT: pull_request
APPLY_FIXES_MODE: commit

# Validation settings
VALIDATE_ALL_CODEBASE: true # Set to false to validate only diff with main branch

# File exclusions
EXCLUDED_DIRECTORIES:
  - .venv
  - .terraform
  - node_modules
  - .git
  - megalinter-reports

# Linters to disable
# DISABLE:
#   - COPYPASTE # Can be noisy for template code
#   - SPELL # Can be too strict

# Terraform linters
TERRAFORM_TFLINT_ARGUMENTS: "--config .tflint.hcl"
TERRAFORM_TERRAFORM_FMT_ARGUMENTS: "-recursive"
TERRAFORM_CHECKOV_ARGUMENTS: "--compact --quiet"

# Python linters
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT # Use default
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_CONFIG_FILE: pyproject.toml

# Markdown linters
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true # Don't fail on broken links

# YAML linters
YAML_PRETTIER_CONFIG_FILE: .prettierrc.json
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml

# JSON linters
JSON_PRETTIER_CONFIG_FILE: .prettierrc.json

# Bash/Shell linters
BASH_SHELLCHECK_ARGUMENTS: "-e SC1091" # Exclude sourcing errors

# Git/GitHub specific
ACTION_ACTIONLINT_ARGUMENTS: "-shellcheck="

# Report settings
PRINT_ALPACA: false # Disable ASCII art for cleaner logs
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false # Disable file.io reporter
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true

# Performance settings
PARALLEL: true
