# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/9.1.0/config-file/
# and all available linters at https://megalinter.io/9.1.0/all-linters/

# Apply fixes automatically (configured in workflow, not here)
# APPLY_FIXES, APPLY_FIXES_EVENT, and APPLY_FIXES_MODE are workflow-level variables

# Validation settings
VALIDATE_ALL_CODEBASE: true # Set to false to validate only diff with main branch

# File exclusions
EXCLUDED_DIRECTORIES:
  - .venv
  - .terraform
  - node_modules
  - .git
  - megalinter-reports

# Linters to disable
DISABLE:
  - SPELL_LYCHEE # Disable link checker (broken links in template URLs)
  - SPELL_CSPELL # Disable cspell (spelling checker)
  - EDITORCONFIG # Disable for now (newline issues)
  - YAML_V8R # Disable YAML schema validation (workflow schema issues)
  - REPOSITORY_GRYPE # Disable grype (dependency vulnerability scanner)
  - REPOSITORY_KICS # Disable KICS (infrastructure security scanner)
  - REPOSITORY_TRIVY # Disable trivy (container/dependency scanner)
  - MARKDOWN_MARKDOWNLINT # Disable markdownlint (markdown formatting)
DISABLE_LINTERS:
  - SPELL_LYCHEE
  - SPELL_CSPELL
  - YAML_V8R
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - MARKDOWN_MARKDOWNLINT

# Terraform linters
TERRAFORM_TFLINT_ARGUMENTS: "--config .tflint.hcl"
TERRAFORM_TERRAFORM_FMT_ARGUMENTS: "-recursive"
TERRAFORM_CHECKOV_ARGUMENTS: "--compact --quiet"
# Terrascan: skip security group rules that are intentionally template examples
# Users should customize these rules for production use
TERRAFORM_TERRASCAN_ARGUMENTS: "--skip-rules AC_AWS_0321,AC_AWS_0322"
TERRAFORM_TERRASCAN_DIRECTORY: terraform

# Python linters
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT # Use default
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_CONFIG_FILE: pyproject.toml

# Markdown linters
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true # Don't fail on broken links

# YAML linters
YAML_PRETTIER_CONFIG_FILE: .prettierrc.json
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml

# JSON linters
JSON_PRETTIER_CONFIG_FILE: .prettierrc.json

# Bash/Shell linters
BASH_SHELLCHECK_ARGUMENTS: "-e SC1091" # Exclude sourcing errors

# Git/GitHub specific
ACTION_ACTIONLINT_ARGUMENTS: "-shellcheck="

# Report settings
PRINT_ALPACA: false # Disable ASCII art for cleaner logs
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false # Disable file.io reporter
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true

# Performance settings
PARALLEL: true
