# Cloud Build Configuration for GCP Deployment
# This file defines the CI/CD pipeline that runs on Google Cloud Build
#
# Trigger this build from GitHub or manually:
#   gcloud builds submit --config=cloudbuild.yaml
#
# Variables (substitutions):
#   _ENVIRONMENT: Target environment (dev, staging, prod)
#   _REGION: GCP region for deployment
#   _SERVICE_NAME: Cloud Run service name

substitutions:
  _ENVIRONMENT: dev
  _REGION: europe-west2
  _SERVICE_NAME: app
  _ARTIFACT_REGISTRY: docker-repo

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  substitution_option: ALLOW_LOOSE

tags:
  - terraform
  - python
  - ci-cd
  - ${_ENVIRONMENT}

# Build steps execute sequentially unless waitFor is specified
steps:
  # ============================================================================
  # STAGE 1: Validation & Security Scanning
  # ============================================================================

  # Step 1.1: Terraform Format Check
  - id: terraform-fmt
    name: hashicorp/terraform:1.10
    entrypoint: sh
    args:
      - -c
      - |
        echo "=== Terraform Format Check ==="
        cd terraform
        terraform fmt -check -recursive -diff
    waitFor: ["-"]

  # Step 1.2: Terraform Validation
  - id: terraform-validate
    name: hashicorp/terraform:1.10
    entrypoint: sh
    args:
      - -c
      - |
        echo "=== Terraform Validation ==="
        cd terraform
        terraform init -backend=false -input=false
        terraform validate
    waitFor: [terraform-fmt]

  # Step 1.3: Terraform Security Scan (tfsec)
  - id: terraform-security
    name: aquasec/tfsec:latest
    args:
      - ./terraform
      - --format
      - json
      - --soft-fail
    waitFor: ["-"]

  # Step 1.4: Infrastructure Security Scan (checkov)
  - id: checkov-scan
    name: bridgecrew/checkov:latest
    entrypoint: checkov
    args:
      - -d
      - ./terraform
      - --framework
      - terraform
      - --compact
      - --quiet
      - --soft-fail
    waitFor: ["-"]

  # Step 1.5: Python Linting (Ruff)
  - id: python-lint
    name: python:3.13-slim
    entrypoint: sh
    args:
      - -c
      - |
        echo "=== Python Linting ==="
        pip install --quiet ruff
        cd python
        ruff check . --output-format=text
        ruff format --check .
    waitFor: ["-"]

  # Step 1.6: Python Security Scan (Bandit)
  - id: python-security
    name: python:3.13-slim
    entrypoint: sh
    args:
      - -c
      - |
        echo "=== Python Security Scan ==="
        pip install --quiet bandit
        cd python
        bandit -r src/ -f txt || true
    waitFor: ["-"]

  # Step 1.7: Secret Scanning (gitleaks)
  - id: secret-scan
    name: zricethezav/gitleaks:latest
    entrypoint: sh
    args:
      - -c
      - |
        echo "=== Secret Scanning ==="
        gitleaks detect --source . --verbose --no-git || true
    waitFor: ["-"]

  # ============================================================================
  # STAGE 2: Testing
  # ============================================================================

  # Step 2.1: Python Unit Tests
  - id: python-tests
    name: python:3.13-slim
    entrypoint: sh
    args:
      - -c
      - |
        echo "=== Python Tests ==="
        pip install --quiet pytest pytest-cov
        cd python
        pip install -e . || true
        pytest tests/ -v --cov=src --cov-report=term-missing || true
    waitFor: [python-lint]

  # ============================================================================
  # STAGE 3: Build Docker Image (if Dockerfile exists)
  # ============================================================================

  # Step 3.1: Build Container Image
  - id: docker-build
    name: gcr.io/cloud-builders/docker
    entrypoint: sh
    args:
      - -c
      - |
        if [ -f "Dockerfile" ]; then
          echo "=== Building Docker Image ==="
          docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA} .
          docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest .
        else
          echo "No Dockerfile found, skipping build"
        fi
    waitFor: [python-tests, terraform-validate]

  # Step 3.2: Push Container Image to Artifact Registry
  - id: docker-push
    name: gcr.io/cloud-builders/docker
    entrypoint: sh
    args:
      - -c
      - |
        if [ -f "Dockerfile" ]; then
          echo "=== Pushing Docker Image ==="
          docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}
          docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest
        else
          echo "No Dockerfile found, skipping push"
        fi
    waitFor: [docker-build]

  # ============================================================================
  # STAGE 4: Terraform Plan (for non-main branches)
  # ============================================================================

  # Step 4.1: Terraform Plan
  - id: terraform-plan
    name: hashicorp/terraform:1.10
    entrypoint: sh
    args:
      - -c
      - |
        echo "=== Terraform Plan ==="
        cd terraform

        # Initialize with GCS backend
        terraform init \
          -backend-config="bucket=${PROJECT_ID}-terraform-state" \
          -backend-config="prefix=terraform/state/${_ENVIRONMENT}" \
          -input=false

        # Create plan
        terraform plan \
          -var="project_name=${PROJECT_ID}" \
          -var="environment=${_ENVIRONMENT}" \
          -var="gcp_project_id=${PROJECT_ID}" \
          -var="gcp_region=${_REGION}" \
          -out=tfplan \
          -input=false
    waitFor: [terraform-validate, terraform-security, checkov-scan]

  # ============================================================================
  # STAGE 5: Terraform Apply (main branch only - manual trigger recommended)
  # ============================================================================

  # Step 5.1: Terraform Apply (requires manual approval in production)
  # Uncomment this step when ready for automated deployments
  # - id: terraform-apply
  #   name: hashicorp/terraform:1.10
  #   entrypoint: sh
  #   args:
  #     - -c
  #     - |
  #       if [ "${BRANCH_NAME}" = "main" ] && [ "${_ENVIRONMENT}" != "prod" ]; then
  #         echo "=== Terraform Apply (${_ENVIRONMENT}) ==="
  #         cd terraform
  #         terraform apply -auto-approve tfplan
  #       else
  #         echo "Skipping auto-apply for branch ${BRANCH_NAME} or prod environment"
  #       fi
  #   waitFor: [terraform-plan]

  # ============================================================================
  # STAGE 6: Deploy to Cloud Run (if applicable)
  # ============================================================================

  # Step 6.1: Deploy to Cloud Run
  - id: deploy-cloud-run
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - -c
      - |
        if [ -f "Dockerfile" ] && [ "${_ENVIRONMENT}" != "prod" ]; then
          echo "=== Deploying to Cloud Run (${_ENVIRONMENT}) ==="
          gcloud run deploy ${_SERVICE_NAME}-${_ENVIRONMENT} \
            --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA} \
            --region=${_REGION} \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars="ENVIRONMENT=${_ENVIRONMENT}" \
            --memory=512Mi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --quiet
        else
          echo "Skipping Cloud Run deployment"
        fi
    waitFor: [docker-push, terraform-plan]

  # ============================================================================
  # STAGE 7: Notifications & Cleanup
  # ============================================================================

  # Step 7.1: Build Summary
  - id: build-summary
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - -c
      - |
        echo "=============================================="
        echo "          BUILD SUMMARY                       "
        echo "=============================================="
        echo "Project ID:    ${PROJECT_ID}"
        echo "Branch:        ${BRANCH_NAME}"
        echo "Commit SHA:    ${SHORT_SHA}"
        echo "Environment:   ${_ENVIRONMENT}"
        echo "Region:        ${_REGION}"
        echo "=============================================="
        echo "Build completed successfully!"
    waitFor:
      - terraform-plan
      - python-tests
      - secret-scan

# Artifacts to save after build
artifacts:
  objects:
    location: gs://${PROJECT_ID}-build-artifacts/${BUILD_ID}
    paths:
      - terraform/tfplan

# Build timeout (default is 10 minutes)
timeout: 1800s
