name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏

  - type: dropdown
    id: project-type
    attributes:
      label: Project Type
      description: What type of project is this bug related to?
      options:
        - Terraform
        - Python
        - GitHub Actions
        - Pre-commit hooks
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Run command '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide relevant environment information
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, macOS 12.0, Windows 11]
        - Python version: [e.g. 3.9.7]
        - Terraform version: [e.g. 1.6.0]
        - Pre-commit version: [e.g. 2.20.0]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/error messages
      description: If applicable, add error messages or logs to help explain your problem
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, configuration files, etc.