name: Pre-commit (Auto-fix on PR)

on:
  pull_request:
    branches: [main, develop, 'feature/**', 'hotfix/**']
  workflow_dispatch: {}

permissions:
  contents: write        # needed to push fixes to PR branches in same repo
  actions: read
  pull-requests: write

jobs:
  pre-commit:
    name: Run & Auto-fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest

      - name: Set up Python
        run: uv python install 3.11

      - name: Install pre-commit
        run: uv tool install pre-commit

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Bootstrap default config if missing (optional)
        run: |
          if [ ! -f ".pre-commit-config.yaml" ]; then
            cat > .pre-commit-config.yaml << 'EOF'
          repos:
            - repo: https://github.com/pre-commit/pre-commit-hooks
              rev: v4.6.0
              hooks:
                - id: trailing-whitespace
                - id: end-of-file-fixer
                - id: check-yaml
                - id: check-json
                - id: pretty-format-json
                  args: ['--autofix']
            - repo: https://github.com/astral-sh/ruff-pre-commit
              rev: v0.8.0
              hooks:
                - id: ruff
                  args: [--fix]
                - id: ruff-format
            - repo: https://github.com/antonbabenko/pre-commit-terraform
              rev: v1.96.1
              hooks:
                - id: terraform_fmt
                - id: terraform_validate
          EOF
          fi

      - name: Run pre-commit (autofix)
        run: |
          pre-commit install
          # run on all files so new repos get cleaned
          pre-commit run --all-files --show-diff-on-failure || true
          # capture whether anything changed
          if ! git diff --quiet; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
        id: pc

      - name: Auto-commit fixes to PR branch
        if: steps.pc.outputs.changed == 'true' && github.event.pull_request.head.repo.fork == false
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pre-commit): auto-fix formatting & lint"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          branch: ${{ github.head_ref }}

      - name: Fail if fixes needed but from a fork (cannot push)
        if: steps.pc.outputs.changed == 'true' && github.event.pull_request.head.repo.fork == true
        run: |
          echo "::error::Pre-commit produced changes but this PR is from a fork; can't push fixes automatically."
          echo "Please run pre-commit locally and push the updated branch."
          exit 1